// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Companies = sequelize.define('companies', {
    companiesId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
  }, {
    tableName: 'companies',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Companies.associate = (models) => {
    Companies.hasOne(models.users, {
      foreignKey: {
        name: 'companiesIdKey',
        field: 'companies_id',
      },
      sourceKey: 'companiesId',
      as: 'user',
    });
    Companies.hasOne(models.panInfo, {
      foreignKey: {
        name: 'companiesIdKey',
        field: 'companies_id',
      },
      sourceKey: 'companiesId',
      as: 'panInfo',
    });
    Companies.hasMany(models.transactions, {
      foreignKey: {
        name: 'companiesIdKey',
        field: 'companies_id',
      },
      sourceKey: 'companiesId',
      as: 'companyTransactions',
    });
  };

  return Companies;
};
